/* error_no.h.  Generated by wanjiang.  */
#ifndef __INCerror_noh
#define __INCerror_noh

#define PPP_ERR_NO		(-100)
#define API_ERR_NO		(-200)

#define PPP_E_IPC_SENDMSG		(PPP_ERR_NO - 1)
#define PPP_E_USERNAME_TOOLONG		(PPP_ERR_NO - 2)
#define PPP_E_PASSWORD_TOOLONG		(PPP_ERR_NO - 3)
#define PPP_E_INVALID_NUMBER		(PPP_ERR_NO - 4)
#define PPP_E_ENCAP_PROTOCOL		(PPP_ERR_NO - 5)

#define API_E_INVALID_PARAMTER		(API_ERR_NO - 1)
#define API_E_INVALID_HANDLETYPE		(API_ERR_NO - 2)
#define API_E_NO_SUCH_INTERFACE		(API_ERR_NO - 3)
#ifdef NIP_API_PPP
#define API_E_NO_SUCH_PROTOCOL		(API_ERR_NO - 4)
#endif
#define API_E_ENCAP_PROTOCOL		(API_ERR_NO - 4)
/* zhuzhm : interface */
#define IF_GERNERAL_ERR_NO		(2 << 16)
#define IF_E_INVALID_IFNAME		(IF_GERNERAL_ERR_NO | 1)

#ifdef HDLC_ZHANKA_INIT
#define HDLC_ERR_NO                   (-100)
#define HDLC_E_TMP                    (HDLC_ERR_NO - 0)
#define HDLC_E_CANNOT_SOCKET          (HDLC_ERR_NO - 1)
#define HDLC_E_CANNOT_SET_PARAMETAR   (HDLC_ERR_NO - 2)
#define HDLC_E_KEEPALIVE_NOT_IN_RANGE (HDLC_ERR_NO - 3)
#define HDLC_E_TIMEOUT_NOT_IN_RANGE   (HDLC_ERR_NO - 4)
#define HDLC_E_CANNOT_SET_DEBUG       (HDLC_ERR_NO - 5)  
#define HDLC_E_IS_NOT_RUNNING_THIS_IF (HDLC_ERR_NO - 6)
#endif /* HDLC_ZHANKA_INIT */

#ifdef SUB_VLAN_ZHANKA
#define SUB_VLAN_ERR_NO                   (-100)
#define SUB_VLAN_E_TMP                    (SUB_VLAN_ERR_NO - 0)
#define SUB_VLAN_E_CANNOT_SET_DEBUG       (SUB_VLAN_ERR_NO - 1)
#define SUB_VLAN_E_VLAN_ID_IS_USED        (SUB_VLAN_ERR_NO - 2)
#define SUB_VLAN_E_VLAN_IS_ALREADY_SET    (SUB_VLAN_ERR_NO - 3)
#endif /* SUB_VLAN_ZHANKA */

#endif
