#ifndef UILIB_PROPERTY_SET_H
#define UILIB_PROPERTY_SET_H

namespace AutoUIFactory
{
	DECLARE_PROPERTYSET_BEGIN( CFlatButton, CButtonPropertySet )
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CSkinScroll , CWndPropertySet )
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CSkinHeaderCtrl , CWndPropertySet )
	DECLARE_PROPERTYSET_END
	
	DECLARE_PROPERTYSET_BEGIN( CFlatDDButton , CWndPropertySet )
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CCheckButton , CButtonPropertySet )
	DECLARE_PROPERTYSET_END
	
	DECLARE_PROPERTYSET_BEGIN( CSkinFrame , CWndPropertySet )
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CSkinListCtrl , CWndPropertySet )
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CSkinDDListCtrl , CWndPropertySet )
	DECLARE_PROPERTYSET_END
	
	DECLARE_PROPERTYSET_BEGIN( CSkinSlider , CSliderCtrlPropertySet )
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CSkinEdit , CWndPropertySet )
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CSkinIPCtrl , CIPAddressCtrlPropertySet  )
	DECLARE_PROPERTYSET_END
	
	DECLARE_PROPERTYSET_BEGIN( CStaticEx , CWndPropertySet )
    AddProperty( "BkTransparent", "StaticExBkTransparent");
	AddProperty( "TextColor", "StaticExTextColor");  
	AddProperty( "FontSize", "StaticExFontSize"); 
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CSkinComboBox , CWndPropertySet )
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CBMPDlg , CWndPropertySet )
	DECLARE_PROPERTYSET_END
	
	DECLARE_PROPERTYSET_BEGIN( CSkinSpinCtrl , CWndPropertySet )
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CSkinGroup , CWndPropertySet )
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CTextButton30 , CWndPropertySet )
	DECLARE_PROPERTYSET_END
	
	DECLARE_PROPERTYSET_BEGIN( CSkinTab , CWndPropertySet )
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CSkinSheet , CWndPropertySet )
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CSkinPage , CWndPropertySet )
	DECLARE_PROPERTYSET_END
	
	DECLARE_PROPERTYSET_BEGIN( CSkinCheckList , CWndPropertySet )
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CColourPopup , CWndPropertySet )
	DECLARE_PROPERTYSET_END

	DECLARE_PROPERTYSET_BEGIN( CColorSelCtrl , CWndPropertySet )
	DECLARE_PROPERTYSET_END
	
	DECLARE_PROPERTYSET_BEGIN( CSkinDateTime , CWndPropertySet )
	DECLARE_PROPERTYSET_END
} // namespace AutoUIFactory end
#endif